[project]
name = "imlightgbm"
version = "0.1.2"
description = "LightGBM for handling label-imbalanced data with focal and weighted loss functions in binary and multiclass classification"
readme = "README.md"
authors = [
    { name = "RektPunk", email = "rektpunk@gmail.com" }
]
license = "MIT"
requires-python = ">=3.10"
dependencies = [
    "lightgbm>=4.5.0",
    "scikit-learn>=1.5.2",
]

[project.urls]
repository = "https://github.com/RektPunk/Imbalance-LightGBM"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.ruff.lint]
select = ["B", "E", "F", "I", "UP", "SIM"]
ignore = ["E501", "TRY003"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
