[project]
name = "imlightgbm"
version = "0.1.1"
description = "LightGBM for label-imbalanced data with focal and weighted loss function"
authors = ["RektPunk <rektpunk@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/RektPunk/Imbalance-LightGBM"
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]
requires-python = ">=3.10"
dependencies = [
    "lightgbm>=4.5.0",
    "scikit-learn>=1.5.2",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
]
